apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: log-writer
          image: log-writer:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
        - name: log-reader
          image: log-reader:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8000"
            - name: COUNTER_FILE
              value: "/usr/src/app/data/counter.txt"
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
            - name: shared-data
              mountPath: /usr/src/app/data
