apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-backend-configmap
data:
  PORT: "3000"
  DB_HOST: "todo-postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "tododb"
  GCS_BUCKET: "todo-db-backup-bucket"
  NATS_URL: "nats://my-nats.project.svc.cluster.local:4222"

