apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
  # Note: secret.yaml is managed separately (encrypted with SOPS)
resources:
- configmap.yaml
- postgres.yaml
- deployment.yaml
- service.yaml
- cronjob.yaml
- backup-cronjob.yaml
images:
- name: PROJECT/TODO_BACKEND
  newName: gcr.io/dwk-gke-482214/todo-backend
  newTag: 28c777e1953e5dcf3d040d0157634f479212c26a
- name: PROJECT/TODO_BACKUP
  newName: gcr.io/dwk-gke-482214/todo-backup
  newTag: 28c777e1953e5dcf3d040d0157634f479212c26a
- name: PROJECT/TODO_CRONJOB
  newName: gcr.io/dwk-gke-482214/todo-cronjob
  newTag: 28c777e1953e5dcf3d040d0157634f479212c26a
