apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  # Note: secret.yaml is managed separately (encrypted with SOPS)
  - configmap.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
  - backup-cronjob.yaml
images:
  - name: PROJECT/TODO_BACKEND
    newName: gcr.io/dwk-gke-482214/todo-backend
  - name: PROJECT/TODO_CRONJOB
    newName: gcr.io/dwk-gke-482214/todo-cronjob
  - name: PROJECT/TODO_BACKUP
    newName: gcr.io/dwk-gke-482214/todo-backup

