apiVersion: ENC[AES256_GCM,data:w/I=,iv:wBi07nCxYDe2uF4ARXr+n9MDHNvM1neOjfWKihrTGt0=,tag:9ZgHeNhS5t4GFMK9FgViIg==,type:str]
kind: ENC[AES256_GCM,data:ZDsfP9bC,iv:0PtXvuUNTPyVQEQPn+n8ea/HGYi7teMIhndTv90PsGA=,tag:blxgMcFDHMKI0uYcBYnU5w==,type:str]
metadata:
    namespace: ENC[AES256_GCM,data:b80eLHV4iQ==,iv:UuLI8BJIiXOkDIr0paLHlNV1cAhQartABvlZrFDmFy8=,tag:heIZBu+SIgCSLzIu2wEuZg==,type:str]
    name: ENC[AES256_GCM,data:K4/z4j8MKkKkH+UwD032Fagtm/A=,iv:iF9AkZdz6fu56uAzVVUXrWtXMLs4s1d9RksAet7ZAkc=,tag:USUbiqtpbiXrLQFuU43Esg==,type:str]
type: ENC[AES256_GCM,data:q+DK2lkh,iv:nDKYGfkO2XFDMBUqNVUtrnTo6wqh/ZmoFCrWPty9MpE=,tag:wHXdxmFY2Hk7RZ8xPpDw8g==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ZuWsxkXy2JM=,iv:Cei/sqO796kIHwc35y8SuoILkFo1b05Z+f2+Cm2o9D8=,tag:cG4WJga4DYVqBEE0EVxctA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EoZ+DNHd2sK3mZE+,iv:SWFb/RXt5z2ReEhdq/CtbTrxV257NJHHIjvMPIXwTIM=,tag:XuTTHg7/Xgoql4xwgBf3zw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:NtF55k5s,iv:9mdPnEd8sgRWgbl8LAXvvx+puSAa3pWgtsXuLbbonpY=,tag:mqp0H4rrBS8LwWlRbyZaHg==,type:str]
sops:
    age:
        - recipient: age15gsxefpq3ddtzwfp8qsa2azv2h6strmtjld07t4lu9nwegp37uhqasphec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUVNnQXh6Qmd3TVBOQWZ6
            Q3k5SjFYODFSMEZraHlCRnZzZ3o4ZXhjT1h3CnljS1hsejNrd2MyR082N2Y0VUhP
            OXRBT3YvQ3hEd0NLVzNRQSszdWpRN1EKLS0tIEg0Y0VaaDlXRmdzaERDdXJ5UzJS
            dTM4Q0dueThabEJmaHhXTXVhbVd5dTgKwpeC3+0vKCs02dtfwSxNcOEJnrmZoAZT
            Mrvm9gGPD8ic4DJimVCgnjk36Pf4FaP06MCrRNCDQ/3rTdPQfQ5oHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T15:25:13Z"
    mac: ENC[AES256_GCM,data:bbMQJKAZymAKGtAeDzEvb65Z4oVk5QSwnYxN1nu9YzFBFHfSUf0b8JsJ1h0QO7zmkrxK1Dr3SvY9uyxkxVuWaAZpkelSBYsCf00iXOGdXQOLwKbq4vsohbwMeMLt4nX3KXSm21+MFFjiVCgr2mQX5EDm+eHXgq+uORxEQtC/3X4=,iv:lZpCCQLa1qbh3KApter8Nv80J5cX1yyvPCFt8B3/xqw=,tag:IPgEkqMZW/+kwZXpqVOeMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
