apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
  # Note: secret.yaml is managed separately (encrypted with SOPS)
resources:
- configmap.yaml
- deployment.yaml
images:
- name: PROJECT/BROADCASTER
  newName: gcr.io/dwk-gke-482214/broadcaster
  newTag: 28c777e1953e5dcf3d040d0157634f479212c26a
