apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  # Note: secret.yaml is managed separately (encrypted with SOPS)
  - configmap.yaml
  - deployment.yaml
images:
  - name: PROJECT/BROADCASTER
    newName: gcr.io/dwk-gke-482214/broadcaster

