apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml
images:
- name: gcr.io/dwk-gke-482214/log-reader
  newName: gcr.io/dwk-gke-482214/log-reader
  newTag: 49fe8f1f30a79b34ef4e534f7c0e0c8d2cd9e41a
- name: gcr.io/dwk-gke-482214/log-writer
  newName: gcr.io/dwk-gke-482214/log-writer
  newTag: 49fe8f1f30a79b34ef4e534f7c0e0c8d2cd9e41a
