apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
# Staging: no backup cronjob
patches:
- path: configmap-patch.yaml
images:
- name: PROJECT/TODO_BACKEND
  newName: gcr.io/dwk-gke-482214/todo-backend
  newTag: 2d3b6472dd4bb9e248b50ab73371bc5a1a7b9379
- name: PROJECT/TODO_CRONJOB
  newName: gcr.io/dwk-gke-482214/todo-cronjob
  newTag: 2d3b6472dd4bb9e248b50ab73371bc5a1a7b9379
